### ISSUE TITLE
Support Zig 0.16.x (macOS 26 compatibility blocker)

### ISSUE THREAD

**Issue by dl-alexandre** [burrito-elixir/burrito#221]
## Summary

Burrito 1.5.0 currently pins Zig 0.15.2. On macOS 26.x, Zig 0.15.2 appears incompatible in Burrito packaging workflows (linker errors for fundamental libc symbols), while Zig 0.16.0 works correctly outside Burrito. However, Burrito's `build.zig` and Zig sources are not yet compatible with Zig 0.16.x due to upstream Zig API changes (`std.process.getEnvVarOwned` was removed, `std.zig.CrossTarget` and `std.build.LibExeObjStep` restructured, etc.).

This leaves macOS 26.x users unable to produce Burrito standalone binaries locally.

## Environment

- **macOS**: 26.4.1 (BuildVersion 25E253)
- **Burrito**: 1.5.0 (Hex)
- **Elixir**: 1.19.5 (compiled with Erlang/OTP 28)
- **OTP**: 28 [erts-16.4]
- **Zig (system, via Homebrew)**: 0.16.0

### 1. Zig 0.16.0 works normally on macOS 26.4

```bash
$ zig version
0.16.0

$ cat hello.zig
const std = @import("std");
pub fn main() void {
    std.debug.print("Hello, World!\n", .{});
}

$ zig run hello.zig
Hello, World!
```

### 2. Burrito + Zig 0.15.2 fails on macOS 26.4

With Zig 0.15.2 downloaded from ziglang.org (`zig-aarch64-macos-0.15.2.tar.xz`), the Burrito wrapper build fails with missing libc symbols:

```
error: undefined symbol: _dispatch_queue_create
error: undefined symbol: _dispatch_semaphore_create
error: undefined symbol: _dispatch_semaphore_signal
error: undefined symbol: _dispatch_semaphore_wait
error: undefined symbol: _dispatch_time
error: undefined symbol: _exit
error: undefined symbol: _fcopyfile
error: undefined symbol: _fork
error: undefined symbol: _free
error: undefined symbol: _getcwd
error: undefined symbol: _getenv
error: undefined symbol: _isatty
error: undefined symbol: _malloc_size
error: undefined symbol: _posix_memalign
error: undefined symbol: _realpath$DARWIN_EXTSN
error: undefined symbol: _sigaction
error: undefined symbol: _sigemptyset
error: undefined symbol: _sysctlbyname
error: undefined symbol: _waitpid
```

This appears to be the same class of issue as [ziglang/zig#16118](https://github.com/ziglang/zig/issues/16118) — Zig's bundled libc for macOS 14+ becomes stale across macOS releases.

### 3. Burrito + Zig 0.16.0 also fails

If I bypass Burrito's version check and let it use Zig 0.16.0, the wrapper build fails because Burrito's `build.zig` references Zig APIs that changed or were removed in 0.16:

```
build.zig:28:41: error: root source file struct 'process' has no member named 'getEnvVarOwned'
    const release_path = try std.process.getEnvVarOwned(b.allocator, "__BURRITO_RELEASE_PATH");
                             ~~~~~~~~~~~^~~~~~~~~~~~~~~
```

Also:
- `const CrossTarget = std.zig.CrossTarget;` — `CrossTarget` no longer exists at that path
- `const LibExeObjStep = std.build.LibExeObjStep;` — `LibExeObjStep` no longer exists at that path

## Current Workaround

I made Burrito wrapping conditional in my project's `mix.exs`:

```elixir
defp releases do
  steps = [:assemble]
  steps = if burrito_enabled?(), do: steps ++ [&Burrito.wrap/1], else: steps
  ...
end

defp burrito_enabled? do
  System.get_env("BURRITO_BUILD", "") != ""
end
```

This allows:
- **Local development**: `MIX_ENV=prod mix release` produces a regular OTP release
- **CI**: `BURRITO_BUILD=1 MIX_ENV=prod mix release` on GitHub Actions `macos-latest` / `macos-13` (macOS 14–15.x) where Zig 0.15.2 still works

## Request

Is Zig 0.16.x support planned for Burrito? Happy to help test on macOS 26.x if useful.

**Comment by CptnKirk** [comment]
This is also an issue for Linux distributions, like Arch, that have moved to Zig 0.16.x

**Comment by doawoo** [comment]
I'll work on getting a Zig `0.16.0` release out!

**Comment by doawoo** [comment]
Reviewing a PR for this!

**Comment by CptnKirk** [comment]
Any word on this update?

**Comment by doawoo** [comment]
Just merged the 0.16.0 PR -- Release will go out in the morning (PST)
